# Generated by Django 5.2.18 on 2026-10-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('schools', '0002_alter_classroom_options_alter_enrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'frais de scolarité', 'verbose_name_plural': 'frais de scolarité'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='schools.classroom', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(verbose_name='Date limite'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.fee', verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Carte bancaire'), ('CASH', 'Espèces / Banque')], default='MOBILE_MONEY', max_length=15, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=40, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PAID', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
    ]
