# Generated by Django 5.2.18 on 2026-10-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'inscription', 'verbose_name_plural': 'inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'école', 'verbose_name_plural': 'écoles'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=9, verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.classroom', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
    ]
