# Generated by Django 5.2.18 on 2026-10-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_lesson_options_and_more'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-created'], 'verbose_name': 'résultat', 'verbose_name_plural': 'résultats'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'choix', 'verbose_name_plural': 'choix'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quiz'},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Passé le'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Bonnes réponses'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Nombre de questions'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Bonne réponse'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Réponse proposée'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.PositiveIntegerField(default=50, verbose_name='Seuil de réussite (%)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
